# This single codebase performs generating of subject, verb, article, adjective, and noun, plus sentence assembly.

---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: 8020
  